<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
             xmlns:tns="urn:arnleadservicewsdl"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="urn:hasher">

    <types>
        <xsd:schema targetNamespace="urn:hasher">
            <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
            <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
        </xsd:schema>
    </types>

    <message name="hasherRequest">
        <part name="str" type="xsd:string"/>
    </message>

    <message name="hasherResponse">
        <part name="return" type="xsd:string"/>
    </message>

    <portType name="hasherPortType">
        <operation name="hash">
            <documentation>hasher</documentation>
            <input message="tns:hasherRequest"/>
            <output message="tns:hasherResponse"/>
        </operation>
    </portType>

    <binding name="hasherBinding" type="tns:hasherPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="hash">
            <soap:operation soapAction="urn:arnleadservicewsdl#hash" style="rpc"/>

            <input>
                <soap:body use="encoded" namespace="urn:hasher"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>

            <output>
                <soap:body use="encoded" namespace="urn:hasher"
                           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <service name="hasher">
        <port name="hasherPort" binding="tns:hasherBinding">
            <soap:address location="http://localhost:8000/hasher"/>
        </port>
    </service>
</definitions>