#index:
#    path: /
#    controller: App\Controller\DefaultController::index

dateinfo:
    path: /dateinfo
    controller: App\Controller\DateInfoServiceController::index

hasher:
    path: /hasher
    controller: App\Controller\HasherServiceController::index
